### ISSUE TITLE
关于能否在Windows平台上运行的问题

### ISSUE THREAD

**Issue by yanjialele** [guanghuixu/AnchorCaptioner#5]
作者你好，我是Image Caption方向新手哈，在Windows下载你的源码运行时，有些文件中调用.c文件导包问题出错，在编译成.so类型文件时也出现了报错，可以说明下Windows平台的运行的注意事项么？多有打扰！

**Comment by guanghuixu** [comment]
推荐linux，没尝试过window，window下的环境安装一直都不太友好。我们的代码基于facebook开源的[MMF框架](https://mmf.sh/docs/)，理论上你能装上MMF就能跑；另外还有个第三方库[pycocoevalcap](https://github.com/guanghuixu/AnchorCaptioner/blob/main/projects/M4C_Captioner/README.md)，需要正确安装。可以把你的报错贴上来看看什么问题，感谢关注~
