### ISSUE TITLE
AssertionError: Number of opts should be multiple of 2

### ISSUE THREAD

**Issue by Caroline0728** [guanghuixu/AnchorCaptioner#7]
![image](https://user-images.githubusercontent.com/71076476/137856050-21d9c2b4-3f5c-46b4-b452-f31480882ba0.png)
Hello, author!
Hello, author!I am sorry to bother you, but I kept giving **AssertionError: Number of opts should be multiple of 2** when running pre-training model validation.I print len of opts is 5. What is the function of opts?Why did this happen?I look forward to your reply. Thank you so much!

**Comment by guanghuixu** [comment]
Sorry, I haven't meet this problem yet. But it seems like a key-value pair of incoming parameters, so it needs to be multiple of 2. For example, `--run_type inference` not `inference`. Please recheck your running script to measure the value of `opts`.

**Comment by Caroline0728** [comment]
Hello,Do json files generated by evaluations and tests have to be sent to EvalAI to get metrics?
Can I get metrics directly from the code?If you must, how do you download EvalAI Server?Thanks~

**Comment by guanghuixu** [comment]
1. During training or evaluation, you can see the metric results, such as CIDer. The code of different metrics can be found in [metrics.py](https://github.com/guanghuixu/AnchorCaptioner/blob/main/pythia/modules/metrics.py).
2. The result of test set should be sent to EvalAI Server, please refer to the [TextVQA Challenge 2021](https://eval.ai/web/challenges/challenge-page/874/leaderboard)

**Comment by Caroline0728** [comment]
Thank you very much for your reply!
Does EvalAI have to be installed on Linux?
I evaluated and tested json files on the server and installed Docker and Docker-compose locally, but there was an error when I installed Eval.
I'm reproducing your code, which is very important to me, so I'm sorry to disturb you.

**Comment by guanghuixu** [comment]
You can create a team to join [TextVQA Challenge](https://eval.ai/web/challenges/challenge-page/874/leaderboard), and then you can summit the ```json file``` to the EvalAI server, which will show your test result on the leaderboard.

**Comment by guanghuixu** [comment]
[TextCaps Challenge 2021](https://eval.ai/web/challenges/challenge-page/906/submission)

**Comment by Caroline0728** [comment]
Thank you so much!!!!I have got the result, thank you for your patient answer!



At 2021-11-02 22:18:21, "guanghuixu" ***@***.***> wrote:

TextCaps Challenge 2021

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
